local _, name_space = ...
name_space.sound_dict = { }
name_space.sound_dict["legtab"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_halondrus.ogg", duration = 5, group = "ready"}
name_space.sound_dict["20geistigbehinderte"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_20geistigbehinderte.ogg", duration = 5, group = "ready"}
name_space.sound_dict["250kgold"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_250kgold.ogg", duration = 5, group = "ready"}
name_space.sound_dict["binamlimit"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_binamlimit.ogg", duration = 5, group = "ready"}
name_space.sound_dict["coolejungs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_coolejungs.ogg", duration = 5, group = "ready"}
name_space.sound_dict["felixmurloc"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_felixmurloc.ogg", duration = 5, group = "ready"}
name_space.sound_dict["fred13euro"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fred13euro.ogg", duration = 5, group = "ready"}
name_space.sound_dict["fredhs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fredhs.ogg", duration = 5, group = "ready"}
name_space.sound_dict["gesiteskrank"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_gesiteskrank.ogg", duration = 5, group = "ready"}
name_space.sound_dict["hurensohn"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hurensohn.ogg", duration = 5, group = "ready"}
name_space.sound_dict["istmirzuviel"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_istmirzuviel.ogg", duration = 5, group = "ready"}
name_space.sound_dict["kindersoundboard"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_kindersoundboard.ogg", duration = 5, group = "ready"}
name_space.sound_dict["leahaltdieschnauze1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_leahaltdieschnauze1.ogg", duration = 5, group = "ready"}
name_space.sound_dict["leahaltdieschnauze2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_leahaltdieschnauze2.ogg", duration = 5, group = "ready"}
name_space.sound_dict["lernresistzenz"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_lernresistzenz.ogg", duration = 15, group = "ready"}
name_space.sound_dict["mistgeburten"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mistgeburten.ogg", duration = 5, group = "ready"}
name_space.sound_dict["pimmelbirne"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_pimmelbirne.ogg", duration = 5, group = "ready"}
name_space.sound_dict["scheppert"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_scheppert.ogg", duration = 5, group = "ready"}
name_space.sound_dict["stuhlkreis"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_stuhlkreis.ogg", duration = 5, group = "ready"}
name_space.sound_dict["touch"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_touch.ogg", duration = 5, group = "ready"}
name_space.sound_dict["tygrasmomreinfeiern"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_tygrasmomreinfeiern.ogg", duration = 5, group = "ready"}
name_space.sound_dict["aideen1ei"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_aideen1ei.ogg", duration = 5, group = "ready"}
name_space.sound_dict["fma"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fma.ogg", duration = 5, group = "ready"}
name_space.sound_dict["reinfeiern"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_reinfeiern.ogg", duration = 5, group = "ready"}
name_space.sound_dict["downyi"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_downyi.ogg", duration = 5, group = "ready"}
name_space.sound_dict["danny"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_danny.ogg", duration = 5, group = "ready"}
name_space.sound_dict["dertagistgelaufen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dertagistgelaufen.ogg", duration = 5, group = "ready"}
name_space.sound_dict["23uhr"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_23uhr.ogg", duration = 5, group = "ready"}
name_space.sound_dict["einfachruhig"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_einfachruhig.ogg", duration = 5, group = "ready"}
name_space.sound_dict["svenlegtab"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_svenlegab.ogg", duration = 5, group = "ready"}
name_space.sound_dict["durchkommen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_durchkommen.ogg", duration = 5, group = "ready"}
name_space.sound_dict["loser"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_loser.ogg", duration = 5, group = "ready"}
name_space.sound_dict["duhurensohn"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_duhurensohn.ogg", duration = 4, group = "ready"}
name_space.sound_dict["mspielen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mspielen.ogg", duration = 4, group = "ready"}
name_space.sound_dict["schaffdasnicht"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_schaffdasnicht.ogg", duration = 4, group = "ready"}
name_space.sound_dict["versammeln"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_versammeln.ogg", duration = 4, group = "ready"}
name_space.sound_dict["fangenwiran"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fangenwiran.ogg", duration = 4, group = "ready"}
name_space.sound_dict["tschuessmuckii"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_tschuessmuckii.ogg", duration = 4, group = "ready"}
name_space.sound_dict["ohnetrollen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_ohnetrollen.ogg", duration = 4, group = "ready"}
name_space.sound_dict["mistgeburt2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mistgeburt2.ogg", duration = 4, group = "ready"}
name_space.sound_dict["peinlichaideen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_peinlichaideen.ogg", duration = 4, group = "ready"}
name_space.sound_dict["bitteraus"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_bitteraus.ogg", duration = 4, group = "ready"}
name_space.sound_dict["heals"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_heals.ogg", duration = 4, group = "ready"}
name_space.sound_dict["fliege"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fliege.ogg", duration = 14, group = "ready"}
name_space.sound_dict["versprecher"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_versprecher.ogg", duration = 8, group = "ready"}
name_space.sound_dict["wer-trollt-hier"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_wer-trollt-hier.ogg", duration = 3, group = "ready"}
name_space.sound_dict["scheiße"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_scheiße.ogg", duration = 3, group = "ready"}
name_space.sound_dict["funkcheck"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_funkcheck.ogg", duration = 2, group = "ready"}
name_space.sound_dict["dannyfastfurios"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dannyfastfurios.ogg", duration = 3, group = "ready"}
name_space.sound_dict["fredhs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fredhs.ogg", duration = 3, group = "ready"}
name_space.sound_dict["afdistdiemitte"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_afdistdiemitte.ogg", duration = 3, group = "ready"}
name_space.sound_dict["denkfuehrerschein"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_denkfuehrerschein.ogg", duration = 3, group = "ready"}
name_space.sound_dict["felixanger1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_felixanger1.ogg", duration = 3, group = "ready"}
name_space.sound_dict["kopfweh"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_kopfweh.ogg", duration = 3, group = "ready"}
name_space.sound_dict["sexfelix"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_sexfelix.ogg", duration = 3, group = "ready"}
name_space.sound_dict["wiederda"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_wiederda.ogg", duration = 3, group = "ready"}