local _, name_space = ...
name_space.sound_dict = { }
name_space.sound_dict["20geistigbehinderte"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_20geistigbehinderte.ogg", duration = 4, group = "ready"}
name_space.sound_dict["23uhr"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_23uhr.ogg", duration = 10, group = "ready"}
name_space.sound_dict["afdistdiemitte"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_afdistdiemitte.ogg", duration = 3, group = "ready"}
name_space.sound_dict["allesfotzen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_allesfotzen.ogg", duration = 7, group = "ready"}
name_space.sound_dict["angefasstwerden"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_angefasstwerden.ogg", duration = 3, group = "ready"}
name_space.sound_dict["arschbohrer"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_arschbohrer.ogg", duration = 5, group = "ready"}
name_space.sound_dict["binamlimit"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_binamlimit.ogg", duration = 4, group = "ready"}
name_space.sound_dict["coolejungs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_coolejungs.ogg", duration = 4, group = "ready"}
name_space.sound_dict["caro"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_caro.ogg", duration = 6, group = "ready"}
name_space.sound_dict["dannyfastfurios"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dannyfastfurios.ogg", duration = 4, group = "ready"}
name_space.sound_dict["dannyhs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dannyhs.ogg", duration = 4, group = "ready"}
name_space.sound_dict["dannyhs2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dannyhs2.ogg", duration = 8, group = "ready"}
name_space.sound_dict["dannyhs3"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dannyhs3.ogg", duration = 8, group = "ready"}
name_space.sound_dict["dertagistgelaufen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_dertagistgelaufen.ogg", duration = 5, group = "ready"}
name_space.sound_dict["diskutieren"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_diskutieren.ogg", duration = 3, group = "ready"}
name_space.sound_dict["doner"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_doner.ogg", duration = 8, group = "ready"}
name_space.sound_dict["downyi1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_downyi1.ogg", duration = 3, group = "ready"}
name_space.sound_dict["downyi2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_downyi2.ogg", duration = 3, group = "ready"}
name_space.sound_dict["duhurensohn"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_duhurensohn.ogg", duration = 3, group = "ready"}
name_space.sound_dict["duschen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_duschen.ogg", duration = 3, group = "ready"}
name_space.sound_dict["einfachruhig"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_einfachruhig.ogg", duration = 7, group = "ready"}
name_space.sound_dict["felixmurloc"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_felixmurloc.ogg", duration = 2, group = "ready"}
name_space.sound_dict["flexianger1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_flexianger1.ogg", duration = 6, group = "ready"}
name_space.sound_dict["fma"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fma.ogg", duration = 5, group = "ready"}
name_space.sound_dict["fred13euro"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fred13euro.ogg", duration = 4, group = "ready"}
name_space.sound_dict["fredfurz1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fredfurz1.ogg", duration = 6, group = "ready"}
name_space.sound_dict["fredfurz2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fredfurz2.ogg", duration = 5, group = "ready"}
name_space.sound_dict["fredlegtab"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_fredlegtab.ogg", duration = 10, group = "ready"}
name_space.sound_dict["freduhr"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_freduhr.ogg", duration = 7, group = "ready"}
name_space.sound_dict["funkcheck"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_funkcheck.ogg", duration = 3, group = "ready"}
name_space.sound_dict["geisteskrank"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_geisteskrank.ogg", duration = 6, group = "ready"}
name_space.sound_dict["geodreickfight"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_geodreickfight.ogg", duration = 6, group = "ready"}
name_space.sound_dict["halondrus"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_halondrus.ogg", duration = 6, group = "ready"}
name_space.sound_dict["hauslichegewalt"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hauslichegewalt.ogg", duration = 6, group = "ready"}
name_space.sound_dict["heals"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_heals.ogg", duration = 6, group = "ready"}
name_space.sound_dict["hsfred"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hsfred.ogg", duration = 4, group = "ready"}
name_space.sound_dict["hssven"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hssven.ogg", duration = 4, group = "ready"}
name_space.sound_dict["istmirzuviel"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_istmirzuviel.ogg", duration = 5, group = "ready"}
name_space.sound_dict["kindersoundboard"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_kindersoundboard.ogg", duration = 5, group = "ready"}
name_space.sound_dict["kopfweh"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_kopfweh.ogg", duration = 3, group = "ready"}
name_space.sound_dict["lernresistenz"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_lernresistenz.ogg", duration = 11, group = "ready"}
name_space.sound_dict["malderwildnis"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_malderwildnis.ogg", duration = 4, group = "ready"}
name_space.sound_dict["mistgeburt1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mistgeburt1.ogg", duration = 6, group = "ready"}
name_space.sound_dict["mistgeburt2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mistgeburt2.ogg", duration = 6, group = "ready"}
name_space.sound_dict["mspielen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mspielen.ogg", duration = 3, group = "ready"}
name_space.sound_dict["mundgewichst"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mundgewichst.ogg", duration = 5, group = "ready"}
name_space.sound_dict["muckiigildenlead"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_muckiigildenlead.ogg", duration = 8, group = "ready"}
name_space.sound_dict["neuerwowpatch"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_neuerwowpatch.ogg", duration = 6, group = "ready"}
name_space.sound_dict["nullprozentpull"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_nullprozentpull.ogg", duration = 10, group = "ready"}
name_space.sound_dict["niedriggrau"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_niedriggrau.ogg", duration = 5, group = "ready"}
name_space.sound_dict["ohnetrollen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_ohnetrollen.ogg", duration = 3, group = "ready"}
name_space.sound_dict["pimmelbirne"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_pimmelbirne.ogg", duration = 3, group = "ready"}
name_space.sound_dict["reinfeiern"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_reinfeiern.ogg", duration = 6, group = "ready"}
name_space.sound_dict["schaffdasnicht"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_schaffdasnicht.ogg", duration = 8, group = "ready"}
name_space.sound_dict["scheise1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_scheise1.ogg", duration = 3, group = "ready"}
name_space.sound_dict["scheise2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_scheise2.ogg", duration = 3, group = "ready"}
name_space.sound_dict["scheppert"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_scheppert.ogg", duration = 4, group = "ready"}
name_space.sound_dict["schmeisicheuchvomdiscord"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_schmeisicheuchvomdiscord.ogg", duration = 8, group = "ready"}
name_space.sound_dict["sexaideen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_sexaideen.ogg", duration = 3, group = "ready"}
name_space.sound_dict["sexfelix"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_sexfelix.ogg", duration = 3, group = "ready"}
name_space.sound_dict["solchepulls"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_solchepulls.ogg", duration = 5, group = "ready"}
name_space.sound_dict["strick"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_strick.ogg", duration = 3, group = "ready"}
name_space.sound_dict["stuhlkreis"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_stuhlkreis.ogg", duration = 3, group = "ready"}
name_space.sound_dict["svenlegab"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_svenlegab.ogg", duration = 6, group = "ready"}
name_space.sound_dict["svenlegtab2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_svenlegtab2.ogg", duration = 5, group = "ready"}
name_space.sound_dict["thorbenanger1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_thorbenanger1.ogg", duration = 5, group = "ready"}
name_space.sound_dict["touch"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_touch.ogg", duration = 3, group = "ready"}
name_space.sound_dict["tschuessmuckii"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_tschuessmuckii.ogg", duration = 6, group = "ready"}
name_space.sound_dict["versammeln"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_versammeln.ogg", duration = 6, group = "ready"}
name_space.sound_dict["wargut"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_wargut.ogg", duration = 5, group = "ready"}
name_space.sound_dict["wiederda"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_wiederda.ogg", duration = 2, group = "ready"}
name_space.sound_dict["zimtbrtchen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_zimtbrtchen.ogg", duration = 4, group = "ready"}
name_space.sound_dict["zoimuh"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_zoimuh.ogg", duration = 3, group = "ready"}
name_space.sound_dict["downyi3"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_downyi3.ogg", duration = 3, group = "ready"}
name_space.sound_dict["flexianger2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_flexianger2.ogg", duration = 5, group = "ready"}
name_space.sound_dict["flexianger3"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_flexianger3.ogg", duration = 10, group = "ready"}
name_space.sound_dict["gildentreffen"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_gildentreffen.ogg", duration = 3, group = "ready"}
name_space.sound_dict["hauslichegewalt2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hauslichegewalt2.ogg", duration = 3, group = "ready"}
name_space.sound_dict["kritik"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_kritik.ogg", duration = 8, group = "ready"}
name_space.sound_dict["svenanger1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_svenanger1.ogg", duration = 8, group = "ready"}
name_space.sound_dict["warclean"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_warclean.ogg", duration = 3, group = "ready"}
name_space.sound_dict["zusammenschlagen1"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_zusammenschlagen1.ogg", duration = 3, group = "ready"}
name_space.sound_dict["zusammenschlagen2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_zusammenschlagen2.ogg", duration = 6, group = "ready"}
name_space.sound_dict["battleshout"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_battleshout.ogg", duration = 6, group = "ready"}
name_space.sound_dict["gameplay"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_gameplay.ogg", duration = 5, group = "ready"}
name_space.sound_dict["holapapi"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_holapapi.ogg", duration = 2, group = "ready"}
name_space.sound_dict["thorbenhs"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_thorbenhs.ogg", duration = 5, group = "ready"}
name_space.sound_dict["hstoni"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_hstoni.ogg", duration = 5, group = "ready"}
name_space.sound_dict["vollfotzenmongo"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_vollfotzenmongo.ogg", duration = 6, group = "ready"}
name_space.sound_dict["zoimuh2"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_zoimuh2.ogg", duration = 6, group = "ready"}
name_space.sound_dict["gurkensalat"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_gurkensalat.ogg", duration = 7, group = "ready"}
name_space.sound_dict["mentaltoni"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_mentaltoni.ogg", duration = 6, group = "ready"}
name_space.sound_dict["reinfingern"] = {path = "Interface\\Addons\\xSoundboard\\sounds\\ready_reinfingern.ogg", duration = 2, group = "ready"}
